### ISSUE TITLE
Project Setup Guide

### ISSUE THREAD

**Issue by Kashinathpat** [ewt45/winlator-fork#3]
hey @ewt45 

Can you please add a script or guide to setup whole project.
I tried to setup project and somehow able to build apk but it doesn't have obb just 100mb apk which doesn't function.

**Comment by ewt45** [comment]
I didn't modify obb so you can simply use the official obb

**Comment by Kashinathpat** [comment]
I am new to android development I don't know how to put obb file in apk itself.
also I just need to clone open-xr repo in cpp folder right?

**Comment by Kashinathpat** [comment]
@ewt45 how to create imagefs file?

**Comment by wa0101** [comment]
> @ewt45 how to create imagefs file?

download the official winlator and use MT Manager to access its files then copy it to ur generated apk
